<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://SOAP.ups.edu.ec/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="sirveService" targetNamespace="http://SOAP.ups.edu.ec/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://SOAP.ups.edu.ec/" elementFormDefault="unqualified" targetNamespace="http://SOAP.ups.edu.ec/" version="1.0">

  <xs:element name="Haber" type="tns:Haber"/>

  <xs:element name="HaberResponse" type="tns:HaberResponse"/>

  <xs:complexType name="Haber">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="HaberResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="HaberResponse">
    <wsdl:part element="tns:HaberResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="Haber">
    <wsdl:part element="tns:Haber" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="sirve">
    <wsdl:operation name="Haber">
      <wsdl:input message="tns:Haber" name="Haber">
    </wsdl:input>
      <wsdl:output message="tns:HaberResponse" name="HaberResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="sirveServiceSoapBinding" type="tns:sirve">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Haber">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="Haber">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="HaberResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="sirveService">
    <wsdl:port binding="tns:sirveServiceSoapBinding" name="sirvePort">
      <soap:address location="http://localhost:8080/SOAP/sirve"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>