package ec.edu.ups.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2021-02-15T02:39:09.664-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://SOAP.ups.edu.ec/", name = "sirve")
@XmlSeeAlso({ObjectFactory.class})
public interface Sirve {

    @WebMethod(operationName = "Suma")
    @RequestWrapper(localName = "Suma", targetNamespace = "http://SOAP.ups.edu.ec/", className = "ec.edu.ups.soap.Suma")
    @ResponseWrapper(localName = "SumaResponse", targetNamespace = "http://SOAP.ups.edu.ec/", className = "ec.edu.ups.soap.SumaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double suma(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1
    );

    @WebMethod
    @RequestWrapper(localName = "multiplicacion", targetNamespace = "http://SOAP.ups.edu.ec/", className = "ec.edu.ups.soap.Multiplicacion")
    @ResponseWrapper(localName = "multiplicacionResponse", targetNamespace = "http://SOAP.ups.edu.ec/", className = "ec.edu.ups.soap.MultiplicacionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double multiplicacion(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1
    );

    @WebMethod
    @RequestWrapper(localName = "divicion", targetNamespace = "http://SOAP.ups.edu.ec/", className = "ec.edu.ups.soap.Divicion")
    @ResponseWrapper(localName = "divicionResponse", targetNamespace = "http://SOAP.ups.edu.ec/", className = "ec.edu.ups.soap.DivicionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double divicion(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1
    );

    @WebMethod(operationName = "Resta")
    @RequestWrapper(localName = "Resta", targetNamespace = "http://SOAP.ups.edu.ec/", className = "ec.edu.ups.soap.Resta")
    @ResponseWrapper(localName = "RestaResponse", targetNamespace = "http://SOAP.ups.edu.ec/", className = "ec.edu.ups.soap.RestaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double resta(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1
    );
}
