package ec.edu.ups.soap;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2021-02-08T18:35:34.347-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://SOAP.ups.edu.ec/", name = "sirve")
@XmlSeeAlso({ObjectFactory.class})
public interface Sirve {

    @WebMethod(operationName = "Haber")
    @RequestWrapper(localName = "Haber", targetNamespace = "http://SOAP.ups.edu.ec/", className = "ec.edu.ups.soap.Haber")
    @ResponseWrapper(localName = "HaberResponse", targetNamespace = "http://SOAP.ups.edu.ec/", className = "ec.edu.ups.soap.HaberResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String haber();
}
