package ec.edu.ups.crud;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2021-02-15T02:06:51.474-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "sirvePersonaService", 
                  wsdlLocation = "file:/C:/Users/aloja/AppData/Local/Temp/tempdir463668506364137686.tmp/sirvePersona_1.wsdl",
                  targetNamespace = "http://CRUD.ups.edu.ec/") 
public class SirvePersonaService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://CRUD.ups.edu.ec/", "sirvePersonaService");
    public final static QName SirvePersonaPort = new QName("http://CRUD.ups.edu.ec/", "sirvePersonaPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/aloja/AppData/Local/Temp/tempdir463668506364137686.tmp/sirvePersona_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SirvePersonaService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/aloja/AppData/Local/Temp/tempdir463668506364137686.tmp/sirvePersona_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SirvePersonaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SirvePersonaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SirvePersonaService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SirvePersonaService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SirvePersonaService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SirvePersonaService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SirvePersona
     */
    @WebEndpoint(name = "sirvePersonaPort")
    public SirvePersona getSirvePersonaPort() {
        return super.getPort(SirvePersonaPort, SirvePersona.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SirvePersona
     */
    @WebEndpoint(name = "sirvePersonaPort")
    public SirvePersona getSirvePersonaPort(WebServiceFeature... features) {
        return super.getPort(SirvePersonaPort, SirvePersona.class, features);
    }

}
